default:
  data_preparation:
    # The name of the cohort
    cohort_name: "age16"
    
    # Child birth date filters the cohort by age
    child_birth_date_min: "01/01/2004"
    child_birth_date_max: "31/12/2008"
    
    # The cohort should live continuously in NL in the following period
    child_live_start: 15
    child_live_end: 16
    
    # The cohort is allowed to be unregistered for this many days 
    # in this period
    child_live_slack_days: 31
    
    # Should we use the address registration of a child on a specific age
    childhood_home_age: 15

   # Postal code link to homes will be considered on this target date
    postcode_target_date: "31/12/2025"
    # Neighbourhood geo link to homes will be considered on this target date
    gwb_target_date: "31/12/2025"
    # Corop geo link to homes will be considered on this target date
    corop_target_date: "31/12/2025"
    
    # Income will be deflated to cpi_base_year euros.
    cpi_base_year: 2024
    
    # Parent income year range
    parent_income_year_min: 2019
    parent_income_year_max: 2023
    
    # Parent wealth year range
    parent_wealth_year_min: 2019
    parent_wealth_year_max: 2023
    
    # high school data year range
    high_school_year_min: 2020
    high_school_year_max: 2024

    # age at which we measure health outcomes
    health_outcome_age: 15
    # health outcomes year range, one year before last time in 8th grade
    health_year_min: 2019
    health_year_max: 2023

    # primary school class year range
    primary_classroom_year_min: 2015
    primary_classroom_year_max: 2020

    # secondary school data range
    secondary_school_year_min: 2019
    secondary_school_year_max: 2023
    
    # ages at which we measure neighborhood composition
    neighborhood_composition_age_1: 12
    neighborhood_composition_age_2: 16

    
  file_locations:
    # The data folder is the root folder of the cbs microdata tables
    data_folder: "G:/"
    # The scratch folder is used to write intermediate output
    scratch_folder: "scratch/age16"
    
   # path to the cbs microdata
    gba_data: "Bevolking/GBAPERSOONTAB/2024/GBAPERSOON2024TABV3.sav"
    gbaao_data: "Bevolking/GBAADRESOBJECTBUS/GBAADRESOBJECT2024BUSV1.sav"
    kind_data: "Bevolking/KINDOUDERTAB/KINDOUDER2024TABV1.sav"
    postcode_data: "BouwenWonen/VSLPOSTCODEBUS/VSLPOSTCODEBUSV2025031.sav"
    vslgwb_data: "BouwenWonen/VSLGWBTAB/VSLGWB2025TAB03V1.sav"
    woon_data: "BouwenWonen/LEVCYCLWOONNIETWOONBUS/LEVCYCLWOONNIETWOONBUSV2024122.sav"
    household_data: "Bevolking/GBAHUISHOUDENSBUS/GBAHUISHOUDENS2024BUSV1.sav"


    # resources
    cpi_index_data: "resources/Consumentenprijzen__prijsindex_2015_100_14112022_221558.xlsx"
    migration_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/LANDAKTUEELREFV13.SAV"
    corop_data: "K:/Utilities/HULPbestanden/GebiedeninNederland/GIN"
    opleiding_data: "K:/Utilities/Code_Listings/SSBreferentiebestanden/OPLEIDINGSNRREFV34.SAV"
